name: mazeplug
version: 1.0
description: Creates a random maze for pvp play
author: 15kingben
main: me.ben.mazeplug.Main
commands:
  create:
    description: create a maze with given parameters
    permission: maze.create
    usage: /create <width> <passage width> OR /create will get values from config
  startMatch:
    description: start the match and teleport players into the maze
    permission: maze.operator
  stopMatch:
    description: stop the match
    permission: maze.operator
  DeleteMaze:
    description: delete a built maze
    permission: maze.create
  joinMatch:
    description: puts you on a list to join the match
    permission: maze.canjoin

permissions:
  maze.create:
    description: ability to create/delete mazes 
    default: op
  maze.operator:
    description: control of starting matches
    default: op
  maze.canjoin:
    description: ability to join maze matches
    default: true